### ISSUE TITLE
IoC Hash

### ISSUE THREAD

**Issue by Still34** [JPCERTCC/Lazarus-research#1]
I noticed that there isn't a hash list available for the IoCs. Will the hashes be disclosed at all? Thanks for the hard work!

**Comment by shu-tom** [comment]
Other IoCs are published on the following blogs:

https://blogs.jpcert.or.jp/en/2020/08/Lazarus-malware.html
https://blogs.jpcert.or.jp/en/2020/09/BLINDINGCAN.html
https://blogs.jpcert.or.jp/en/2021/01/Lazarus_tools.html
https://blogs.jpcert.or.jp/en/2021/01/Lazarus_malware2.html
https://blogs.jpcert.or.jp/en/2021/03/Lazarus_malware3.html
